### ISSUE TITLE
如何处理抓取过程卡住的问题

### ISSUE THREAD

**Issue by chjq201410695** [xjkj123/Lianjia#9]
问题如下图所示：

![image](https://user-images.githubusercontent.com/29965893/59208659-1e5d2e80-8bdc-11e9-9606-67570901684d.png)

每次到第二步的时候都会卡在某处，如图是卡在了这个区域的70%处，即使挂一天都不再动了。

只能重启程序然后重新爬，但是又会卡在某处。 第二步我跑了三天了还是没有顺利爬完。

请问怎么解决这个问题，怎么从上次卡住的地方接着爬取，而不是只能重新开始。

**Comment by xjkj123** [comment]
程序只是写了个思路,具体的爬取过程没有细分哦,可以仔细阅读代码自己造个车
